const LS_KEY='waveloop_demo_v2';
const getState=()=>{try{return JSON.parse(localStorage.getItem(LS_KEY))||{registrations:[],referrals:[],messages:[],lastRef:null}}catch{return{registrations:[],referrals:[],messages:[],lastRef:null}}};
const setState=s=>localStorage.setItem(LS_KEY,JSON.stringify(s)); const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const names=['Aarav','Meera','Karthik','Nandini','Vignesh','Riya','Sanjay','Harsha','Ananya','Pranav','Ishita','Rahul']; const colleges=['Example Institute of Technology','South Valley Engineering College','Kongu Tech University','Riverside College of Engineering']; const sources=['Campus ambassador','Referral','Telegram / community','LinkedIn / Instagram'];
const seed=()=>{const s=getState();for(let i=0;i<18;i++){const email=`demo${i+1}@example.com`;if(!s.registrations.some(r=>r.email===email)){const code=`DEMO-${String(i+1).padStart(3,'0')}`;s.registrations.push({id:`demo-${i+1}`,name:names[i%names.length],email,college:colleges[i%colleges.length],branch:['CSE','IT','ECE'][i%3],year:i%5===0?'2026':'2027',goal:['Build a first AI project','Improve my resume','Prepare for interviews'][i%3],source:sources[i%4],referralCode:code,referredBy:i>2?`DEMO-${String((i%4)+1).padStart(3,'0')}`:'',createdAt:new Date(Date.now()-i*3600000).toISOString(),qualified:i%5!==0});}} s.referrals=s.registrations.filter(r=>r.referredBy).map(r=>({from:r.referredBy,to:r.referralCode,createdAt:r.createdAt,verified:r.qualified}));setState(s);render()};
const render=()=>{const s=getState();$('#kpiRegs').textContent=s.registrations.length;$('#kpiQualified').textContent=s.registrations.filter(r=>r.qualified).length;$('#kpiReferrals').textContent=s.referrals.length;renderTable(s);renderLeaders(s);renderChannels();renderSim()};
function renderTable(s){$('#regTable').innerHTML=s.registrations.slice(-18).reverse().map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.college)}</td><td>${esc(r.branch)}</td><td>${esc(r.year)}</td><td>${esc(r.source)}</td><td>${esc(r.referredBy||'—')}</td><td class="qual">${r.qualified?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="7">No demo registrations yet.</td></tr>'}
function renderLeaders(s){const counts={};s.registrations.forEach(r=>{if(r.referredBy&&r.qualified)counts[r.referredBy]=(counts[r.referredBy]||0)+1});const rows=[['Campus Crew',17],['Code Circle',14],['Project Ninjas',11],['Build Buddies',9],['AI First',7],...Object.entries(counts).map(([name,score])=>[name,score])].map(x=>({name:x[0],score:+x[1]})).sort((a,b)=>b.score-a.score);$('#leaderboard').innerHTML=rows.slice(0,8).map((r,i)=>`<div class="leader-row"><span class="rank">${i+1}</span><div><b>${esc(r.name)}</b><small>${r.score} verified referrals</small></div><span class="score">${r.score}</span></div>`).join('')}
function renderChannels(){const base=[['Campus ambassadors',200],['Referral loop',120],['Placement communities',110],['LinkedIn / Instagram',70]];const total=500;$('#channels').innerHTML=base.map(([n,v])=>`<div class="channel-row"><span>${n}</span><div class="track"><div class="fill" style="width:${v/200*100}%"></div></div><b>${v}</b></div>`).join('')+`<div class="channel-row" style="margin-top:7px"><span><strong>Total planned</strong></span><div></div><b>${total}</b></div>`;$('#budgetRecommendation').textContent='Watch ambassadors + referral loop'}
const vals=[40,120,200,280,360,440,500];function renderSim(progress=null){const data=progress?vals.map((v,i)=>i<=progress?v:0):vals;const max=500;$('#simChart').innerHTML=data.map((v,i)=>`<div class="bar-col"><b>${v||'—'}</b><div class="bar" style="height:${Math.max(8,(v||0)/max*175)}px"></div><span>D${i+1}</span></div>`).join('')}
let simTimer=null;$('#runSim').addEventListener('click',()=>renderSim());$('#animateSim').addEventListener('click',()=>{let i=0;clearInterval(simTimer);renderSim(0);simTimer=setInterval(()=>{renderSim(i);i++;if(i>6){clearInterval(simTimer)}},450)});
const msgTemplates={en:{direct:'Free 60-minute AI project workshop for final-year students. Build one live project you can explain in an interview. I’m registered — join me here: [your referral link]',peer:'I’m joining a free 60-minute AI build workshop for 2027 batch students. Want to build together? Here’s my link: [your referral link]',urgency:'24 hours left to grab a spot for a free 60-minute AI project build session. Come with a friend and leave with something you can explain: [your referral link]'},ta:{direct:'2027 batch மாணவர்களுக்கு free 60-minute AI project workshop. Interview-ல் explain செய்யக்கூடிய ஒரு live project build பண்ணலாம். Join: [your referral link]',peer:'நான் ஒரு free 60-minute AI build workshop-க்கு register பண்ணிட்டேன். நாம friends-ஆ சேர்ந்து build பண்ணலாமா? [your referral link]',urgency:'24 hours left! 60-minute AI project workshop-க்கு ஒரு friend-ஐ கூட அழைத்துக் கொண்டு join பண்ணலாம்: [your referral link]'},te:{direct:'2027 batch students కోసం free 60-minute AI project workshop. Interviewలో explain చేయగల live project build చేద్దాం. Join: [your referral link]',peer:'నేను free 60-minute AI build workshopకి register అయ్యాను. కలిసి build చేద్దామా? నా link: [your referral link]',urgency:'24 hours left! ఒక friendతో కలిసి free 60-minute AI project workshopలో join అవ్వండి: [your referral link]'}};
$('#generate').addEventListener('click',()=>{$('#messageOut').value=msgTemplates[$('#lang').value][$('#messageTone').value]+`\n\nChannel: ${$('#messageChannel').value}`});
$('#copyMessage').addEventListener('click',async()=>{const t=$('#messageOut').value;if(!t)return;try{await navigator.clipboard.writeText(t);$('#copyMessage').textContent='Copied ✓';setTimeout(()=>$('#copyMessage').textContent='Copy message',1200)}catch{alert(t)}});
$('#seed').addEventListener('click',seed);$('#clearDemo').addEventListener('click',()=>{if(confirm('Clear browser demo registrations and referrals?')){localStorage.removeItem(LS_KEY);render()}});
$('#exportCsv').addEventListener('click',()=>{const rows=getState().registrations;if(!rows.length){alert('No demo registrations to export.');return}const headers=['name','email','college','branch','year','goal','source','referralCode','referredBy','qualified','createdAt'];const csv=[headers.join(','),...rows.map(r=>headers.map(h=>`"${String(r[h]??'').replace(/"/g,'""')}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='waveloop-demo-registrations.csv';a.click();URL.revokeObjectURL(a.href)});
render();
